# Generated by Django 4.0.3 on 2022-07-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binvo',
            old_name='copy_bin_number',
            new_name='bin_number',
        ),
        migrations.RenameField(
            model_name='binvo',
            old_name='copy_bin_size',
            new_name='bin_size',
        ),
        migrations.RenameField(
            model_name='binvo',
            old_name='copy_closet_name',
            new_name='closet_name',
        ),
        migrations.RenameField(
            model_name='binvo',
            old_name='copy_href',
            new_name='href',
        ),
    ]
